apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
  name: {{ .Chart.name }}-{{ .Chart.appVersion }}
  namespace: production
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    env: prod
